apiVersion: v1
kind: Secret
metadata:
  name: powerstore-config
  namespace: csi-powerstore
type: Opaque
stringData:
  config: |
    arrays:
      - endpoint: "https://<POWERSTORE_IP>/api/rest"
        globalID: "<POWERSTORE_GLOBAL_ID>"
        username: "<POWERSTORE_USER>"
        password: "<POWERSTORE_PASSWORD>"
        blockProtocol: "iSCSI"
        isDefault: true
        insecure: true
