# csi-powerstore Helm values — Harvester target (Air-gap).
# Image references point at the local Hauler registry.
images:
  driver:
    image: hauler-registry.local:5000/dell/container-storage-modules/csi-powerstore:v2.17.0
  attacher:
    image: hauler-registry.local:5000/sig-storage/csi-attacher:v4.11.0
  provisioner:
    image: hauler-registry.local:5000/sig-storage/csi-provisioner:v6.2.0
  snapshotter:
    image: hauler-registry.local:5000/sig-storage/csi-snapshotter:v8.5.0
  resizer:
    image: hauler-registry.local:5000/sig-storage/csi-resizer:v2.1.0
  registrar:
    image: hauler-registry.local:5000/sig-storage/csi-node-driver-registrar:v2.16.0
  healthmonitor:
    image: hauler-registry.local:5000/sig-storage/csi-external-health-monitor-controller:v0.17.0
  replication:
    image: hauler-registry.local:5000/dell/container-storage-modules/dell-csi-replicator:v1.15.0
  podmon:
    image: hauler-registry.local:5000/dell/container-storage-modules/podmon:v1.16.0
  metadataretriever:
    image: hauler-registry.local:5000/dell/container-storage-modules/csi-metadata-retriever:v1.14.0
  authorization:
    image: hauler-registry.local:5000/dell/container-storage-modules/csm-authorization-sidecar:v2.5.0
